[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "yotils"
dynamic = ["version"]
description = "A Python utility library"
readme = "README.md"
requires-python = ">=3.14"
license = {file = "LICENSE"}
authors = [
    {name = "Andrei Kobyshev", email = "yokotoka@users.noreply.github.com"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]

[project.urls]
Homepage = "https://github.com/yokotoka/yotils"
Repository = "https://github.com/yokotoka/yotils"

[tool.hatch.version]
path = "yotils/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["yotils"]
